<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Buat user untuk siswa (10 siswa)
        $users = [
            [
                'name' => 'Andi Wijaya',
                'username' => 'andi_wijaya',
                'email' => 'andi.wijaya@siswa.com',
                'password' => Hash::make('password123'),
                'role' => 'siswa',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Siti Nurhaliza',
                'username' => 'siti_nurhaliza',
                'email' => 'siti.nurhaliza@siswa.com',
                'password' => Hash::make('password123'),
                'role' => 'siswa',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Budi Setiawan',
                'username' => 'budi_setiawan',
                'email' => 'budi.setiawan@siswa.com',
                'password' => Hash::make('password123'),
                'role' => 'siswa',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rina Anggraini',
                'username' => 'rina_anggraini',
                'email' => 'rina.anggraini@siswa.com',
                'password' => Hash::make('password123'),
                'role' => 'siswa',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dedi Kurniawan',
                'username' => 'dedi_kurniawan',
                'email' => 'dedi.kurniawan@siswa.com',
                'password' => Hash::make('password123'),
                'role' => 'siswa',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maya Sari',
                'username' => 'maya_sari',
                'email' => 'maya.sari@siswa.com',
                'password' => Hash::make('password123'),
                'role' => 'siswa',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fajar Ramadhan',
                'username' => 'fajar_ramadhan',
                'email' => 'fajar.ramadhan@siswa.com',
                'password' => Hash::make('password123'),
                'role' => 'siswa',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lina Marlina',
                'username' => 'lina_marlina',
                'email' => 'lina.marlina@siswa.com',
                'password' => Hash::make('password123'),
                'role' => 'siswa',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hendra Gunawan',
                'username' => 'hendra_gunawan',
                'email' => 'hendra.gunawan@siswa.com',
                'password' => Hash::make('password123'),
                'role' => 'siswa',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Putri Ayu',
                'username' => 'putri_ayu',
                'email' => 'putri.ayu@siswa.com',
                'password' => Hash::make('password123'),
                'role' => 'siswa',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($users as $userData) {
            DB::table('users')->insert($userData);
        }

        // Ambil user_id yang baru dibuat
        $userIds = DB::table('users')
            ->where('role', 'siswa')
            ->pluck('id', 'email');

        // Ambil ID kelas
        $kelasIds = DB::table('kelas')->pluck('id');

        // Insert data siswa
        DB::table('siswa')->insert([
            [
                'user_id' => $userIds['andi.wijaya@siswa.com'],
                'nis' => '2024001',
                'nama' => 'Andi Wijaya',
                'tempat_lahir' => 'Jakarta',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2008-05-15',
                'alamat' => 'Jl. Kenanga No. 10, Jakarta',
                'no_hp' => '081234560001',
                'tahun_masuk' => '2024',
                'url_photo' => 'https://ui-avatars.com/api/?name=Andi+Wijaya&background=random',
                'url_cover' => null,
                'is_active' => true,
                'kelas_id' => $kelasIds[0] ?? null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['siti.nurhaliza@siswa.com'],
                'nis' => '2024002',
                'nama' => 'Siti Nurhaliza',
                'tempat_lahir' => 'Bandung',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2008-08-20',
                'alamat' => 'Jl. Melati No. 15, Jakarta',
                'no_hp' => '081234560002',
                'tahun_masuk' => '2024',
                'url_photo' => 'https://ui-avatars.com/api/?name=Siti+Nurhaliza&background=random',
                'url_cover' => null,
                'is_active' => true,
                'kelas_id' => $kelasIds[0] ?? null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['budi.setiawan@siswa.com'],
                'nis' => '2024003',
                'nama' => 'Budi Setiawan',
                'tempat_lahir' => 'Surabaya',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2008-03-10',
                'alamat' => 'Jl. Mawar No. 20, Jakarta',
                'no_hp' => '081234560003',
                'tahun_masuk' => '2024',
                'url_photo' => 'https://ui-avatars.com/api/?name=Budi+Setiawan&background=random',
                'url_cover' => null,
                'is_active' => true,
                'kelas_id' => $kelasIds[1] ?? null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['rina.anggraini@siswa.com'],
                'nis' => '2024004',
                'nama' => 'Rina Anggraini',
                'tempat_lahir' => 'Medan',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2008-11-25',
                'alamat' => 'Jl. Anggrek No. 5, Jakarta',
                'no_hp' => '081234560004',
                'tahun_masuk' => '2024',
                'url_photo' => 'https://ui-avatars.com/api/?name=Rina+Anggraini&background=random',
                'url_cover' => null,
                'is_active' => true,
                'kelas_id' => $kelasIds[1] ?? null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['dedi.kurniawan@siswa.com'],
                'nis' => '2023001',
                'nama' => 'Dedi Kurniawan',
                'tempat_lahir' => 'Semarang',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2007-06-12',
                'alamat' => 'Jl. Dahlia No. 8, Jakarta',
                'no_hp' => '081234560005',
                'tahun_masuk' => '2023',
                'url_photo' => 'https://ui-avatars.com/api/?name=Dedi+Kurniawan&background=random',
                'url_cover' => null,
                'is_active' => true,
                'kelas_id' => $kelasIds[2] ?? null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['maya.sari@siswa.com'],
                'nis' => '2023002',
                'nama' => 'Maya Sari',
                'tempat_lahir' => 'Yogyakarta',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2007-09-18',
                'alamat' => 'Jl. Tulip No. 12, Jakarta',
                'no_hp' => '081234560006',
                'tahun_masuk' => '2023',
                'url_photo' => 'https://ui-avatars.com/api/?name=Maya+Sari&background=random',
                'url_cover' => null,
                'is_active' => true,
                'kelas_id' => $kelasIds[2] ?? null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['fajar.ramadhan@siswa.com'],
                'nis' => '2023003',
                'nama' => 'Fajar Ramadhan',
                'tempat_lahir' => 'Palembang',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2007-04-22',
                'alamat' => 'Jl. Sakura No. 7, Jakarta',
                'no_hp' => '081234560007',
                'tahun_masuk' => '2023',
                'url_photo' => 'https://ui-avatars.com/api/?name=Fajar+Ramadhan&background=random',
                'url_cover' => null,
                'is_active' => true,
                'kelas_id' => $kelasIds[3] ?? null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['lina.marlina@siswa.com'],
                'nis' => '2023004',
                'nama' => 'Lina Marlina',
                'tempat_lahir' => 'Makassar',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2007-12-08',
                'alamat' => 'Jl. Flamboyan No. 14, Jakarta',
                'no_hp' => '081234560008',
                'tahun_masuk' => '2023',
                'url_photo' => 'https://ui-avatars.com/api/?name=Lina+Marlina&background=random',
                'url_cover' => null,
                'is_active' => true,
                'kelas_id' => $kelasIds[3] ?? null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['hendra.gunawan@siswa.com'],
                'nis' => '2022001',
                'nama' => 'Hendra Gunawan',
                'tempat_lahir' => 'Bali',
                'jenis_kelamin' => 'L',
                'tanggal_lahir' => '2006-07-30',
                'alamat' => 'Jl. Cempaka No. 9, Jakarta',
                'no_hp' => '081234560009',
                'tahun_masuk' => '2022',
                'url_photo' => 'https://ui-avatars.com/api/?name=Hendra+Gunawan&background=random',
                'url_cover' => null,
                'is_active' => true,
                'kelas_id' => $kelasIds[4] ?? null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['putri.ayu@siswa.com'],
                'nis' => '2022002',
                'nama' => 'Putri Ayu',
                'tempat_lahir' => 'Pontianak',
                'jenis_kelamin' => 'P',
                'tanggal_lahir' => '2006-02-14',
                'alamat' => 'Jl. Orchid No. 11, Jakarta',
                'no_hp' => '081234560010',
                'tahun_masuk' => '2022',
                'url_photo' => 'https://ui-avatars.com/api/?name=Putri+Ayu&background=random',
                'url_cover' => null,
                'is_active' => true,
                'kelas_id' => $kelasIds[4] ?? null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
